apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: dbaasproviders.dbaas.redhat.com
spec:
  group: dbaas.redhat.com
  names:
    kind: DBaaSProvider
    listKind: DBaaSProviderList
    plural: dbaasproviders
    singular: dbaasprovider
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: DBaaSProvider is the Schema for the dbaasproviders API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DBaaSProviderSpec defines the desired state of DBaaSProvider
            properties:
              allowsFreeTrial:
                description: AllowsFreeTrial indicates whether the provider provides
                  free trials
                type: boolean
              connectionKind:
                description: ConnectionKind is the name of the connection resource
                  (CRD) defined by the provider
                type: string
              credentialFields:
                description: CredentialFields indicates what information to collect
                  from UX & how to display fields in a form
                items:
                  properties:
                    displayName:
                      description: A user-friendly name for this field
                      type: string
                    key:
                      description: The name for this field
                      type: string
                    required:
                      description: If this field is required or not
                      type: boolean
                    type:
                      description: The type of field (string, maskedstring, integer,
                        boolean)
                      type: string
                  required:
                  - displayName
                  - key
                  - required
                  - type
                  type: object
                type: array
              instanceKind:
                description: InstanceKind is the name of the instance resource (CRD)
                  defined by the provider for provisioning
                type: string
              instanceParameterSpecs:
                description: InstanceParameterSpecs  indicates what parameters to
                  collect from UX & how to display fields in a form in order to provision
                  an instance
                items:
                  properties:
                    displayName:
                      description: A user-friendly name for this parameter
                      type: string
                    name:
                      description: The name for this field
                      type: string
                    required:
                      description: If this field is required or not
                      type: boolean
                    type:
                      description: The type of parameter (string, maskedstring, integer,
                        boolean)
                      type: string
                  required:
                  - displayName
                  - name
                  - required
                  - type
                  type: object
                type: array
              instanceParameterValues:
                description: InstanceParameterValues  indicates what parameter values
                  are displayed in UX for users to select
                items:
                  properties:
                    displayValue:
                      type: string
                    id:
                      description: Unique ID for the value
                      type: integer
                    isDefault:
                      description: Indicate whether this is a default for the same
                        parent value
                      type: boolean
                    name:
                      type: string
                    parent:
                      description: Parent parameter value
                      type: integer
                    value:
                      type: string
                  required:
                  - id
                  - isDefault
                  - name
                  - value
                  type: object
                type: array
              inventoryKind:
                description: InventoryKind is the name of the inventory resource (CRD)
                  defined by the provider
                type: string
              provider:
                description: Provider contains information about database provider
                  & platform
                properties:
                  displayDescription:
                    description: DisplayDescription indicates the description text
                      shown for a Provider within UX (e.g. developerâ€™s catalog tile)
                    type: string
                  displayName:
                    description: A user-friendly name for this database provider (e.g.
                      'MongoDB Atlas')
                    type: string
                  icon:
                    description: Icon information indicates what logo we display on
                      developer catalog tile
                    properties:
                      base64data:
                        type: string
                      mediatype:
                        type: string
                    required:
                    - base64data
                    - mediatype
                    type: object
                  name:
                    description: Indicates the name used to specify Service Binding
                      origin parameter (e.g. 'Red Hat DBaas / MongoDB Atlas')
                    type: string
                required:
                - displayDescription
                - displayName
                - icon
                - name
                type: object
            required:
            - allowsFreeTrial
            - connectionKind
            - credentialFields
            - instanceKind
            - instanceParameterSpecs
            - instanceParameterValues
            - inventoryKind
            - provider
            type: object
          status:
            description: DBaaSProviderStatus defines the observed state of DBaaSProvider
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
