# permissions for end users to view dbaasconnections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dbaasconnection-viewer-role
rules:
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dbaas.redhat.com
  resources:
  - dbaasconnections/status
  verbs:
  - get
