apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    categories: Database
    description: Import provider cloud instances for easy coupling with developer
      applications.
  name: dbaas-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: DBaaSConnection is the Schema for the dbaasconnections API
      displayName: DBaaS Connection
      kind: DBaaSConnection
      name: dbaasconnections.dbaas.redhat.com
      version: v1alpha1
    - description: DBaaSInventory is the Schema for the dbaasinventory API
      displayName: DBaaS Inventory
      kind: DBaaSInventory
      name: dbaasinventories.dbaas.redhat.com
      version: v1alpha1
  description: Import provider cloud instances for easy coupling with developer applications.
  displayName: Database-as-a-Service Operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAH8AAAB/CAYAAADGvR0TAAABhWlDQ1BJQ0MgcHJvZmlsZQAAKJF9kT1Iw0AYht+mlkppcbCDiEOG6mRBrIijVqEIFUKt0KqDyaV/0KQhSXFxFFwLDv4sVh1cnHV1cBUEwR8QNzcnRRcp8bum0CLGO457eO97X+6+A4RmlWlW3wSg6baZSSXFXH5VDL4iQDOCBEIys4w5SUrDc3zdw8f3uzjP8q77c0TUgsUAn0g8ywzTJt4gnt60Dc77xFFWllXic+Jxky5I/Mh1xeU3zqU2CzwzamYz88RRYrHUw0oPs7KpEU8Rx1RNp3wh57LKeYuzVq2zzj35C8MFfWWZ67RGkMIiliBBhII6KqjCRpx2nRQLGTpPeviH236JXAq5KmDkWEANGuS2H/wPfvfWKiYm3aRwEgi8OM7HKBDcBVoNx/k+dpzWCeB/Bq70rr/WBGY+SW90tdgRMLANXFx3NWUPuNwBhp4M2ZTbkp+WUCwC72f0TXlg8BYIrbl965zj9AHIUq/SN8DBITBWoux1j3f39/bt35pO/34APopykmk+AbkAAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAALiMAAC4jAXilP3YAAAAHdElNRQflBQUNNht+wpQZAAAAGXRFWHRDb21tZW50AENyZWF0ZWQgd2l0aCBHSU1QV4EOFwAAC2NJREFUeNrtnXtwU1Uex7/nJm3api/SdFtaoAW1sq5Q2iIyjoAIqMWFobCyiA9kUFhRWVHAYRkGcQTHXVbtwIjoziLC6rIu6C6PusyqPIVSoKUtr1ke7bRA2qYhfSVpc2/u/hFSWps0z5ucm5zvDDMQknuT+/n+fud3fveeewnCRAYAraMhSr2fxFMgmjA5ZoSBjlxDEAY8co1AGPDINQJh0CPXBIRBj1wTEAY9ck1AGPTINQFh0CkwwWlCNKIY/vAZeHqyAGHQI9cEhIGPXANIDr+GQfdZ2aek5UNYtEduFiAMfOQagDDwkWsAwsBHrgEIAx+5BuAYeDmJQ12u2mKgJfIZ+OCBb7XGghc77NPASv8zAGHg5Qe+uw/gpwEIAy9P8IEwAGHg5QveXwP4VPAx8PSAB4Cakb7x8DryWa+eLvA9lV/pHU+vIt/AqFAL3hc+xJsNs3RPL3hfxn+PI5+Bpx+8t+M/52nUM9EP3ltebtO+gRC0Fogs6mUCvjv9V7m/KNRt5DPw8gMPADUj3HPjWLoPP/Ce8uNYkRee4D0p/pT9Tu3kfHhTRyNu6lxEDRoC5cBMKGNiAI4DUSoAACIvQOStECwW8A06WGuvoWP/doiGyrAA35OjxtuCTy6dvJR1JYjLHw1Oq5Vk++KtW2j/6SgMb0+XHXiHXHX+iMuopxS+dl0J1I9OBpTK0HwBnkdbyV4Y3imSBXjAdeOHyCHqE+YXQ7NwceiAu5LViqY/rYPpm7XUgu8v+gnNUZ/40iYMeGkxQCi/e4woQv/n99CxcxWV4F1FP6E16occMYPExMiryjSZUDtBTR14V9HP0TivzyoV5AceAOLikFUqUAneGV+Otnl9VqkAcBxkK45D1gkerSSdKvDO5v1UHeXUP/5X3uAdUiiQvvwD+n1KU8qPmzgJ4aLUollUfi+DM/islRtg0TYtdZL6OUZJuumfLNI+LVV+7QMEEAT5g+d5lI+iN64MPeHTlPJrxyrRvm+PLCLHWbQ3/XMnyguiqP6ajtRPAHpP4sQVrUHqmysBlYpu6BYL/rd6BdoPbJSNT/Mrb/dN5XAGT/3bddC8sFCys3feynrzJuo/3QTj7vWyHJmogz+4pAl1hameFdO/nIEBC99A7IiRIImJEvb/RaC9A6Yzp9C8YRVsDRVoFRLAWxv6/VTuj3qcnailGz5NJ3Kyyuxfg79ej+szBvu+oahUxM9dCWWKFsq0dCi0qVCkaEE4BTiF/WIOmyBAtAkQ9HoI+ibwjToIzXq0bXuj3/rYXcv2/v/cRFR6OgCgPJfeE1LZlSCEppTvgN8tQUD7oR/Q/NZjVEyMXIEfVvw9ksY/0qc7STN8oJ/LuKiQQoH4R6cgvkwERBG25ma07NmN1o8XBR+8TQNe1AMA0l7bjLSZT0GhSZH1jJTuyHcnQYDY2QnzyeMwV1eivd+U7b0SXtyEmOH3IXbMWBCVyuvzDrRHvrzheyKbDRBtgIi+vQNC7vyR4IQSS/shH6o5sC62q8GMicFnYvBDKluzPmwOLH/jOoPvjeqeSEXLzr/JHrxu219RVTiITfV8lXZ9CdRTnpAVdMP+vahdOY3N8wOpzG/roMykM5KstTWonj5UlhmKyO3uWklLv0DSk9NBkpJCU5cYjdB/tx/X33tG9sMTdU2eli+3w/jh8159Lq5oDeInToFq6DBwaen+n+ETRfANDTBfvQzD4YMwfLXaq48PXrsL2hkzWYfPW/gOmQ4fRNObE6XZkSIBHUnD0akrC+hm795yDAljH+r+N4PvI/w7edaGtn3/9mFVrOsJTiBX0mSt3wNN4VSn7WHW3vWbFYeEaTOQMO22MUwmtB4owa11vwkJ+MHv7IJ28uOAWs3GfMkj38Mx2qbToUt3A5bqKphPHETXyW0/+6UqtMUMg7XlQr+bUo9bgMQHxyHh/hFQDcyA8vaFGb6Ipf1gwKdUtMNnvX2f5ns2wGJGV20NhBajbNcaKBlJD8XzqN+8CU1/Weo6jaqzMer780BsLIMfLrq59TPoPlrovvToqEH52DgAQF65wOB7I+OX25E89zmq0nt5nsK38d7Hz0Vswddd+P3YBsTHh2bnggD9v75B3dqnXL4lY/nnSJk0GcpkDWxmE9qqzuLqEvktL6e6t5+5qxbKIUOCszNRxJVVK9C6b4PLt+Rsr4B6ZG7vwq9nc8ds7k77DH6gpiSpozFwyy4oBw2WZmUOz7tdXJlX1glERwNtbWjYthX12z7u/r/kMRMwbNUakIwMWUzxuuHTtGInedkOGDc86/Z9MZNeR/Kz86HKGW4H4mfEu1tOnXfCBMTGQjh/DhXzXN9xY8j815D68mK7AUbRPYvOpm2tXlaZCPA8dG8tQefhzR63Ktpic2BtuQjViCJonyxCTNZQxN1zL5TqOEChtKdmheLOZdqOlC2KuPjyCzCX7ui1xZ5LrrpLgWtXUTF7qvuDung5UuYvgM1oxNkJA6iFn08l/B4RaTp2FE1Lx/cLPtC3O8srt98NTGwxorO6GoTjEH1PDs4UPuz5gd1/BCQ1ler0Tzf8n1XgndVV0L2YJyn43B/04FJS0HnyJKpfed7n7aRNn4NBq9+G/tvdqFszi8H3C74TM1gbG2E8ehj1784JXNSfFSEajTgzZazf2yoouwhbixFnxw+gGz4tRV9ATuxYrQDPQzCbYKmvR1eDDkJbG2wWM0TBBtgE3PhgQa+PqB9ZhJziT243mnbgyofv+g+/9Ly91hAElOfT1Uh13Ie3e1CqCRf47tTVhfIHVH0iHoKAa8uWwnD0QEB284vCWciYNx+Ku+4GAJybXYiuS99RE/X2gTPCdHNH7/P8eaUmAMDlV34XMPAA0FiyCxVzfo0LT88CBAG/+kcJff0Tx18ST4FEAnxd8c9O0MTEQmxsQMvpI5Lsz3T5HAxf2ReiZL+/j4qU3we+hgIw5mNHQrLfjtKTkm7/WvF6QBQxYMrjIT/GGmeRT4MaXx8fkvvv8R3t0u/EZrM3mmhM+7Sk/toxXNANkJA7SvqdEGI3ACUpvw98DSWOrH0wBmKHNPeqV2ZN6POaIidH0t+TPuMZgOPQdvwnalK+07Qf+ujn0NoVhYqH4nFt7aqAZ4F7N37eu/rf+hmgUCBv7yHJflHmshX2GcXicdREvVP4mlCD79GyNe5ej/JRHC4seBrotARkD9FZ2b2r/48WwqrTgUtLQ8GhM8h+dSW4GP+vyVcmaTF8XTEKjlcDKhWavt5JVdQDVD1Xz7NeffrvP8XAuc8BfjyDx3SuCpfmjuz12l1bjiGxx1KrQOr65o1o/GRJSKPeY/hAsDt+vp+kSXt1M7STHkP00KFeXehxYd5sWCq+7vO6dt77SH54AhTR/t05mzdboPv7F+g4uCXkNZRXT9QMbvRL9xSq5Jl/gPq+kVBlZCIqLg5EoQCJioJoEyBarbg0rwDhLldR3y/84EQ/fY8fCze5inq3TR5pK38GPhQVvsfwNQy8rKVxS8GNEk8H+nJZBj4YWnRF7ZabR2ADV/wx8KEu8ryK/MClfwaelnTvFXz/iz8GnpYiz+u071/6Z+BpS/deR75v6Z+BpzHd+xT5DnnW/GHgg6n8Su9Z+nQlj/vxn4GndZz3O/L7H/8ZeJrH+YDAd24ABl4u4P2G39sADLycwAcEvsMAdblqiyB2qBgWeYAPGHyHARyP5maiH3xA4TMDyAt8wOEzA8gHvCTwmQHkAV4y+MwA9IOXFL5DZ5gBfFZ+pbR8grI6h2UBeqI96PCZAegDH1T4zAT0QHco6OvzNfDs4sJI0qIrahKKNZIhhRDpWSAU0U4N/Eg1QaihUwU/UkxAC3Qq4YerCWiDTjX8cDEBrdBlAV+ORqAduCzh02wEOQGXPfxQGkKuoJ3p/6/IIJJPW5yWAAAAAElFTkSuQmCC
    mediatype: image/png
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dbaas
  links:
  - name: Database-as-a-Service Operator
    url: https://dbaas-operator.domain
  maintainers:
  - email: jary@redhat.com
    name: Jeremy Ary
  maturity: alpha
  provider:
    name: Red Hat
    url: https://www.redhat.com
  version: 0.0.0
