apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: dbaas-operator
  namespace: openshift-marketplace
spec:
  sourceType: grpc
  image: quay.io/ecosystem-appeng/dbaas-operator-catalog:v0.0.7
  displayName: DBaaS Operator