## Append samples you want in your CSV to this file as resources ##
resources:
- dbaas_v1alpha1_dbaasconnection.yaml
- dbaas_v1alpha1_dbaasinventory.yaml
- dbaas_v1alpha1_dbaasprovider.yaml
- dbaas_v1alpha1_dbaastenant.yaml
- dbaas_v1alpha1_dbaasplatform.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
