
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: dbaasconnections.dbaas.redhat.com
spec:
  group: dbaas.redhat.com
  names:
    kind: DBaaSConnection
    listKind: DBaaSConnectionList
    plural: dbaasconnections
    singular: dbaasconnection
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: DBaaSConnection is the Schema for the dbaasconnections API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: DBaaSConnectionSpec defines the desired state of DBaaSConnection
            properties:
              cluster:
                description: Foo is an example field of DBaaSConnection. Edit dbaasconnection_types.go
                  to remove/update
                properties:
                  connectionString:
                    type: string
                  databaseUser:
                    properties:
                      name:
                        type: string
                      password:
                        format: byte
                        type: string
                    required:
                    - name
                    type: object
                  id:
                    type: string
                  instanceSizeName:
                    type: string
                  name:
                    type: string
                  providerName:
                    type: string
                  regionName:
                    type: string
                required:
                - id
                type: object
              provider:
                description: Provider will be used by ServiceBindingConverter to indicate
                  the provider type for connection desired (WIP)
                type: string
              type:
                description: Type will be used by ServiceBindingConverter to indicate
                  the type of connection desired (WIP)
                type: string
            required:
            - cluster
            - provider
            - type
            type: object
          status:
            description: DBaaSConnectionStatus defines the observed state of DBaaSConnection
            properties:
              dbConfigMap:
                description: DBConfigMap is the name of the ConfigMap containing the
                  connection info
                type: string
              dbCredentials:
                description: DBCredentials is the name of the Secret containing the
                  database credentials
                type: string
            required:
            - dbConfigMap
            - dbCredentials
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
