
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: dbaasproviders.dbaas.redhat.com
spec:
  group: dbaas.redhat.com
  names:
    kind: DBaaSProvider
    listKind: DBaaSProviderList
    plural: dbaasproviders
    singular: dbaasprovider
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: The schema for the DBaaSProvider API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Defines the desired state of a DBaaSProvider object.
            properties:
              allowsFreeTrial:
                description: Indicates whether the provider offers free trials.
                type: boolean
              connectionKind:
                description: The name of the connection's custom resource definition
                  (CRD) as defined by the provider.
                type: string
              credentialFields:
                description: Indicates what information to collect from the user interface
                  and how to display fields in a form.
                items:
                  description: Defines the attributes.
                  properties:
                    displayName:
                      description: A user-friendly name for this field.
                      type: string
                    helpText:
                      description: Additional information about the field.
                      type: string
                    key:
                      description: The name for this field.
                      type: string
                    required:
                      description: Defines if the field is required or not.
                      type: boolean
                    type:
                      description: 'The type of field: string, maskedstring, integer,
                        or boolean.'
                      type: string
                  required:
                  - displayName
                  - key
                  - required
                  - type
                  type: object
                type: array
              externalProvisionDescription:
                description: Instructions on how to provision instances by using the
                  database provider's web portal.
                type: string
              externalProvisionURL:
                description: The URL for provisioning instances by using the database
                  provider's web portal.
                type: string
              instanceKind:
                description: The name of the instance's custom resource definition
                  (CRD) as defined by the provider for provisioning.
                type: string
              inventoryKind:
                description: The name of the inventory custom resource definition
                  (CRD) as defined by the database provider.
                type: string
              provider:
                description: Contains information about database provider and platform.
                properties:
                  displayDescription:
                    description: Indicates the description text shown for a database
                      provider within the user interface. For example, the catalog
                      tile description.
                    type: string
                  displayName:
                    description: A user-friendly name for this database provider.
                      For example, 'MongoDB Atlas'.
                    type: string
                  icon:
                    description: Indicates what icon to display on the catalog tile.
                    properties:
                      base64data:
                        type: string
                      mediatype:
                        type: string
                    required:
                    - base64data
                    - mediatype
                    type: object
                  name:
                    description: The name used to specify the service binding origin
                      parameter. For example, 'Red Hat DBaaS / MongoDB Atlas'.
                    type: string
                required:
                - displayDescription
                - displayName
                - icon
                - name
                type: object
              provisioningParameters:
                additionalProperties:
                  description: Information for a provisioning parameter
                  properties:
                    defaultValues:
                      description: Lists of default values for the field. May have
                        multiple default values based on the dependencies. If default
                        values are present, the field is displayed as a text input
                        field. If both OptionsLists and DefaultValues are present,
                        DefaultValues will be ignored in the UX.
                      items:
                        description: ProvisioningParameterDefaultValue defines the
                          default value for a field based on the dependencies
                        properties:
                          defaultValue:
                            description: Default value
                            type: string
                          dependencies:
                            description: List of the dependent fields and their values
                            items:
                              description: FieldDependency defines the name and value
                                of a field used as a dependency
                              properties:
                                field:
                                  description: Name of the field used as a dependency
                                  enum:
                                  - name
                                  - plan
                                  - cloudProvider
                                  - regions
                                  - availabilityZones
                                  - nodes
                                  - machineType
                                  - storageGib
                                  - spendLimit
                                  - teamProject
                                  - databaseType
                                  - dedicatedLocationLabel
                                  - serverlessLocationLabel
                                  - hardwareLabel
                                  - planLabel
                                  - spendLimitLabel
                                  type: string
                                value:
                                  description: Value of the field used as a dependency
                                  type: string
                              type: object
                            type: array
                        type: object
                      type: array
                    displayName:
                      description: A user-friendly name for this field.
                      type: string
                    helpText:
                      description: Additional info about the field
                      type: string
                    optionsLists:
                      description: Lists of options for the field. May have multiple
                        option lists based on the dependencies. If options lists are
                        present, the field is displayed as a dropdown in the UX
                      items:
                        description: 'ProvisioningParameterOptions defines the list
                          of options available for UX for a field based on the dependencies
                          A single parameter can have multiple option lists depending
                          on the dependent parameters. For instance, there are 4 different
                          lists for regions: one for dedicated cluster on GCP, one
                          for dedicated on AWS, one for serverless on GCP, and one
                          for serverless on AWS.'
                        properties:
                          defaultOption:
                            description: Default option for this option list
                            properties:
                              displayValue:
                                description: Corresponding display value
                                type: string
                              value:
                                description: Value of the option
                                type: string
                            type: object
                          dependencies:
                            description: List of the dependent fields and their values
                            items:
                              description: FieldDependency defines the name and value
                                of a field used as a dependency
                              properties:
                                field:
                                  description: Name of the field used as a dependency
                                  enum:
                                  - name
                                  - plan
                                  - cloudProvider
                                  - regions
                                  - availabilityZones
                                  - nodes
                                  - machineType
                                  - storageGib
                                  - spendLimit
                                  - teamProject
                                  - databaseType
                                  - dedicatedLocationLabel
                                  - serverlessLocationLabel
                                  - hardwareLabel
                                  - planLabel
                                  - spendLimitLabel
                                  type: string
                                value:
                                  description: Value of the field used as a dependency
                                  type: string
                              type: object
                            type: array
                          options:
                            description: Options displayed in the UX
                            items:
                              description: Option defines the value and display value
                                for an option in a dropdown, radio button or checkbox
                              properties:
                                displayValue:
                                  description: Corresponding display value
                                  type: string
                                value:
                                  description: Value of the option
                                  type: string
                              type: object
                            type: array
                        type: object
                      type: array
                  required:
                  - displayName
                  type: object
                description: Parameter specs used by UX for provisioning a database
                  instance
                type: object
            required:
            - allowsFreeTrial
            - connectionKind
            - credentialFields
            - externalProvisionDescription
            - externalProvisionURL
            - instanceKind
            - inventoryKind
            - provider
            type: object
          status:
            description: DBaaSProviderStatus defines the observed state of DBaaSProvider
            properties:
              conditions:
                items:
                  description: "Condition contains details for one aspect of the current
                    state of this API Resource. --- This struct is intended for direct
                    use as an array at the field path .status.conditions.  For example,
                    type FooStatus struct{     // Represents the observations of a
                    foo's current state.     // Known .status.conditions.type are:
                    \"Available\", \"Progressing\", and \"Degraded\"     // +patchMergeKey=type
                    \    // +patchStrategy=merge     // +listType=map     // +listMapKey=type
                    \    Conditions []metav1.Condition `json:\"conditions,omitempty\"
                    patchStrategy:\"merge\" patchMergeKey:\"type\" protobuf:\"bytes,1,rep,name=conditions\"`
                    \n     // other fields }"
                  properties:
                    lastTransitionTime:
                      description: lastTransitionTime is the last time the condition
                        transitioned from one status to another. This should be when
                        the underlying condition changed.  If that is not known, then
                        using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: message is a human readable message indicating
                        details about the transition. This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: observedGeneration represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.conditions[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: reason contains a programmatic identifier indicating
                        the reason for the condition's last transition. Producers
                        of specific condition types may define expected values and
                        meanings for this field, and whether the values are considered
                        a guaranteed API. The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                        --- Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important. The regex it matches is (dns1123SubdomainFmt/)?(qualifiedNameFmt)
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
